### ISSUE TITLE
Removing Nested Keys

### ISSUE THREAD

**Issue by estuart** [repeatedly/fluent-plugin-record-modifier#15]
Hi, first off thank you for this plugin. It is great!

Is there any way to remove nested keys from a json string? Currently removing top level keys works great but I can find no way to remove nested keys.

Thanks

**Comment by repeatedly** [comment]
Currently, fluentd doesn't have unified API for specifiying nested key: https://github.com/fluent/fluentd/pull/1107
This is why record-modifier doesn't support nested key in remove_keys.

I didn't test but following configuration may work.

```aconf
<filter foo>
  @type record_modifier
  <record>
    for_remove ${record["foo"].delete("bar")}
  </record>
  remove_keys for_remove
</filter>
```

**Comment by estuart** [comment]
This seems to do the trick. Thanks!

**Comment by dannyk81** [comment]
@estuart can you share your configuration? I'm unable to get this working with fluentd v0.12 and record_modifier v0.6.0

```
<filter udp.php>
  @type record_modifier
  <record>
    to_remove ${record["http"].delete("env")}
  </record>
  remove_keys to_remove
</filter>
```

The error we are getting:
```
2017-12-19 16:20:24 +0000 [warn]: emit transaction failed: error_class=NoMethodError error="undefined method `delete' for nil:NilClass" location="/var/lib/gems/2.3.0/gems/fluent-plugin-record-modifier-0.6.0/lib/fluent/plugin/filter_record_modifier.rb:156:in `expand'" tag="udp.php"
  2017-12-19 16:20:24 +0000 [warn]: suppressed same stacktrace
2017-12-19 16:20:24 +0000 [error]: forward error error=#<NoMethodError: undefined method `delete' for nil:NilClass> error_class=NoMethodError
```

Here's an event sample:
```
{
        "timestamp": "1513650893625",
        "level": "FATAL",
        "http": {
            "user_agent": "Apache-HttpClient/4.3.3 (java 1.5)",
            "method": "POST",
            "env": {
                "REQUEST_START_TIME": 1513650858,
                "HTTP_ACCEPT_ENCODING": "gzip,deflate",
                "HTTP_CONNECTION": "close",
                "HTTP_CONTENT_LENGTH": "231",
                "HTTP_CONTENT_TYPE": "application/json; charset=UTF-8"
           }
       }
}
```

**Comment by dannyk81** [comment]
Ok, I figured it out :)

Seems it was failing because not all records have the `http` key, so I used the trick mentioned by @repeatedly to check if it exists and delete the nested `env` if true.

```
<filter udp.php>
  @type record_modifier
  <record>
    _dummy_ ${if record.has_key?('http'); record['http'].delete('env') ; end; nil}
  </record>
  remove_keys _dummy_
</filter>
```
